name: Bug Report
description: Report something that isn't working.
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Issue Description
      placeholder: Clearly describe the bug or unexpected behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      placeholder: Provide detailed steps, logs, or screenshots to reproduce the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment Details
      placeholder: OS, browser, versions, and other relevant environment information.

  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: Describe what should have happened instead.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this issue?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute a fix?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
