name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      placeholder: Clearly describe the proposed feature or improvement.
    validations:
      required: true

  - type: textarea
    id: usefulness
    attributes:
      label: Value Proposition
      placeholder: Explain the problem this solves and the value it provides.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to work on this feature?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
