name: Documentation
description: Improvements or issues related to documentation.
title: "[Docs] "
labels: ["documentation"]
body:
  - type: textarea
    attributes:
      label: Documentation Issue
      placeholder: Describe what needs to be documented or corrected (e.g., missing steps, outdated sections, unclear explanations).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Location
      placeholder: Specify where the documentation exists or should be added (e.g., README, wiki, specific file path).

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to work on this documentation issue?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
