name: Maintenance
description: Configuration, refactoring, or general maintenance tasks.
title: "[Maintenance] "
labels: ["maintenance"]
body:
  - type: textarea
    attributes:
      label: Maintenance Task
      placeholder: Describe what needs to be configured or maintained (e.g., CI config, dependencies, refactoring).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Justification
      placeholder: Explain why this maintenance is necessary.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this maintenance task?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to this maintenance task?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
