name: Question
description: Ask a question about this project.
title: "[Question] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **This is not a support ticket system.**

        Use Issues only for questions directly related to this repository.

        For:
        - general help
        - usage questions
        - ideas or brainstorming
        - "how do I...?" questions

        please use [Discussions](https://github.com/orgs/T-Craft-Platforms/discussions/categories/helpdesk-requests) instead.

  - type: textarea
    attributes:
      label: Question
      placeholder: Ask a clear, specific question about this repository.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Context
      placeholder: Relevant code, configuration, or background.
