name: Other
description: Anything that doesn't fit other templates.
title: "[Other] "
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: Provide a detailed description of your issue or topic.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: No existing template fits this issue.
          required: true
