name: Maintenance
description: Configuration, refactoring, or general maintenance tasks.
title: "[Maintenance] "
labels: ["maintenance"]
body:
  - type: textarea
    attributes:
      label: What needs to be configured or maintained?
      placeholder: CI config, Kubernetes settings, version bumps.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this maintenance needed?
      placeholder: Reasoning or background.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this maintenance task?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to this maintenance task?
      options:
        - Yes.
        - No.
    validations:
      required: true
